### ISSUE TITLE
Firebase API Key publicly exposed 

### ISSUE THREAD

**Issue by wantedbear007** [4rjunkum4r/24OnlinePrototype#1]
Hide your API and other credentails using dotenv.

File location: [https://github.com/4rjunkum4r/24OnlinePrototype/blame/master/src/backend/database/firebaseConfig/firebaseConfig.js](url)
And close the issue ones fixed !

**Comment by 4rjunkum4r** [comment]
Thank you brother

**Comment by 4rjunkum4r** [comment]
Thanks for your help bhanu . 😁
